Remove cookies
nhost/hasura-backend-plus pull request #512
Opened 2021-05-10 13:25 UTC by komninoschat

Resolves #505.

2021-05-15 07:46 UTC, elitan commented on src/middlewares/auth.ts
> +    delete req.query.permission_variables
Why do we do this? Looks like a security issue if the permission variables can be set using a query variable.

2021-05-15 07:46 UTC, elitan commented on src/routes/auth/activate.ts
> +    res.redirect(APPLICATION.REDIRECT_URL_SUCCESS.replace('JWT_TOKEN', ticket))
What's the use case here? I feel like `JWT_TOKEN` and `ticket` should not be mixed like this?

2021-05-15 07:46 UTC, elitan commented on src/routes/auth/providers/utils.ts
> +  res.redirect(`${PROVIDERS.REDIRECT_SUCCESS}?refresh_token=${refresh_token}&permission_variables=${permission_variables}`)
Why do we send `permission_variables` here?

2021-05-15 07:46 UTC, elitan commented on src/shared/helpers.ts
> +  const days = JWT.REFRESH_EXPIRES_IN / 1440
Could we add a comment about the `1440` here to increase the code readability?

ex: // converting from minutes to days

2021-05-15 07:46 UTC, elitan commented on src/shared/types.ts
> +  permission_variables?: string
Why is this added here?

2021-06-01 08:59 UTC, elitan requested changes
See previous comments.

2021-06-02 09:41 UTC, elitan submitted a review, later dismissed

2021-06-02 09:41 UTC, elitan commented on src/routes/auth/magic-link.ts
> +  const session: Session = { jwt_token, jwt_expires_in, user, refresh_token, permission_variables }
I don't think we should return `permission_variables` here (or any other place) to the client.

2021-06-02 09:41 UTC, elitan commented on src/routes/auth/magic-link.ts
> +      res.redirect(APPLICATION.REDIRECT_URL_SUCCESS.replace('JWT_TOKEN', token))
What is `.replace('JWT_TOKEN', token)` used for?

2021-06-02 09:51 UTC, elitan commented on src/routes/auth/activate.ts
> +    res.redirect(APPLICATION.REDIRECT_URL_SUCCESS.replace('JWT_TOKEN', ticket))
Let's fix in a separate issue

2021-06-02 10:00 UTC, elitan commented on src/routes/auth/magic-link.ts
> +      res.redirect(APPLICATION.REDIRECT_URL_SUCCESS.replace('JWT_TOKEN', token))
Will be fixed in a separate PR.

2021-06-03 06:51 UTC, merged

2021-06-14 18:53 UTC, nikolowry commented
@komninoschat @elitan will there be updated guidance on how to store the `refresh_token` in the client-side?

Per https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/#refresh_token_persistance, the point of the `HttpOnly` cookie was to avoid storing it in `window.localStorage`. Is persisting the `refresh_token` somehow different than persisting the JWT token?

2021-06-14 20:11 UTC, elitan commented
We recommend using `localStorage`: https://github.com/nhost/nhost-js-sdk/blob/master/src/NhostClient.ts#L31-L33

2021-06-14 21:20 UTC, nikolowry commented
@elitan the best language I could find to express my concerns can be found from [Auth0's blog](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/#Security-considerations):
> Security considerations
Refresh tokens are long-lived. This means when a client gets a refresh token from a server, this token must be stored securely to keep it from being used by potential attackers. If a refresh token is leaked, it may be used to obtain new access tokens (and access protected resources) until it is either blacklisted or it expires (which may take a long time). Refresh tokens must be issued to a single authenticated client to prevent use of leaked tokens by other parties. Access tokens must be kept secret, but as you may imagine, security considerations are less strict due to their shorter life.

Storing the refresh token in `localStorage` seems to be slightly better practice than storing the whole JWT token. It seems like security is taking a step back with this approach, or am I not fully understanding something?

2021-06-15 05:50 UTC, elitan commented
From my perspective, storing the `refresh_token` in `localStorage` is secure enough.

But you can store the refresh token any way you want by specifying a `custom` storage strategy and provide the functions `setItem`, `getItem` and `removeItem` when you initiate the nhost js sdk:

https://github.com/nhost/nhost-js-sdk/blob/master/src/types.ts#L26-L33