Resend confirmation
nhost/hasura-backend-plus pull request #524
Opened 2021-05-24 08:07 UTC by komninoschat

2021-06-01 09:11 UTC, elitan requested changes

2021-06-01 09:11 UTC, elitan commented on db/migrations/00002_add_confirmation_reset_timeout.sql
> +  ADD COLUMN last_sent_confirmation timestamp with time zone DEFAULT now() NOT NULL;
we use `<verb>_at` ex `updated_at` or `created_at` - so I'm suggesting we use `confirmation_email_sent_at` or `last_confirmation_email_sent_at`.

2021-06-01 09:11 UTC, elitan commented on src/routes/auth/resend-confirmation.ts
> +    ) > +new Date()
Can we make this code more readable?

2021-06-01 09:17 UTC, elitan requested changes
There is a lot of discussions in https://github.com/nhost/hasura-backend-plus/issues/237.

One of the suggestions was to adopt this into `/auth/register` and let that endpoint send out a new email (with a timeout) if there is already a user that is inactive.

If we keep this `/auth/resend-confirmation` endpoint, there is no way of telling of a user was already registered or not since we just return "Account already exists" if you try to register an account with an email that's already registered (https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/auth/register.ts#L26-L28).

Do we have any references on how other services and/or auth services handles this?

2021-06-04 07:33 UTC, merged

2021-06-11 20:59 UTC, joshmedeski commented
@elitan any ETA on when this feature will be published?