Allowlist
nhost/hasura-backend-plus pull request #575
Opened 2021-06-07 13:21 UTC by komninoschat

2021-06-10 06:34 UTC, elitan requested changes
- invite email template
- env var if invite email template should be sent or not. Default to `true`.

2021-06-10 06:34 UTC, elitan commented on src/shared/config/authentication/registration.ts
> +    return castBooleanEnv('ALLOWLIST_ENABLE', false)
`_ENABLED`

2021-06-10 07:05 UTC, elitan commented
Do we want to change the table name and endpoint from `allowlist` to something more related to **registration** specifically?

Naming it `auth.allowlist` does not make it clear that it's related to allow registrations. Some people might belive it's related to allow people to login, or to allow people to change password or something else?

2021-06-11 14:59 UTC, merged

2021-06-14 17:53 UTC, nikolowry commented
Sorry for commenting again on an already merged PR, but it be great if either @komninoschat  or @elitan could provide some clarifications on the following:
-  Is the final namespace of this feature settled on? I'm just a little confused with this PR being named "Allowlist" but all the ENV vars being prefixed with `WHITELIST`. Also, https://github.com/nhost/hasura-backend-plus/pull/555/files was closed without being merged or commented on. Maybe I missed the discussion, but is there a link to where this decision was discussed and reached? 
- Semi-related, but how long will `_ENABLED` and `_ENABLE` both be supported? There's a lack of consistency in the docs about which one we should ultimately prefer.

I really appreciate the project and how quick you've guys have been with communication and fixes. Thanks for the hard work!

2021-06-14 20:14 UTC, elitan commented
- It's going to be named [whitelist](https://en.wikipedia.org/wiki/Whitelisting). 
- We're moving from `_ENABLE` to `_ENABLED` so it's safe to start using `_ENABLED`.

Thanks for your kind words.